creation date: '2019-10-15T11:52:24.789062'
tubedb version: '1.12'
region:
  id: BE
  name: Exploratories
groups:
- id: AEG
  name: Schwäbische Alb Grünland
- id: AEW
  name: Schwäbische Alb Wald
- id: HEG
  name: Hainich-Dün Grünland
- id: HEW
  name: Hainich-Dün Wald
- id: SEG
  name: Schorfheide Grünland
- id: SEW
  name: Schorfheide Wald
plots:
- AEG01
- AEG02
- AEG03
- AEG04
- AEG05
- AEG06
- AEG07
- AEG08
- AEG09
- AEG10
- AEG11
- AEG12
- AEG13
- AEG14
- AEG15
- AEG16
- AEG17
- AEG18
- AEG19
- AEG20
- AEG21
- AEG22
- AEG23
- AEG24
- AEG25
- AEG26
- AEG27
- AEG28
- AEG29
- AEG30
- AEG31
- AEG32
- AEG33
- AEG34
- AEG35
- AEG36
- AEG37
- AEG38
- AEG39
- AEG40
- AEG41
- AEG42
- AEG43
- AEG44
- AEG45
- AEG46
- AEG47
- AEG48
- AEG49
- AEG50
- AET06
- AEW01
- AEW02
- AEW03
- AEW04
- AEW05
- AEW06
- AEW07
- AEW08
- AEW09
- AEW10
- AEW11
- AEW12
- AEW13
- AEW14
- AEW15
- AEW16
- AEW17
- AEW18
- AEW19
- AEW20
- AEW21
- AEW22
- AEW23
- AEW24
- AEW25
- AEW26
- AEW27
- AEW28
- AEW29
- AEW30
- AEW31
- AEW32
- AEW33
- AEW34
- AEW35
- AEW36
- AEW37
- AEW38
- AEW39
- AEW40
- AEW41
- AEW42
- AEW43
- AEW44
- AEW45
- AEW46
- AEW47
- AEW48
- AEW49
- AEW50
- HEG01
- HEG02
- HEG03
- HEG04
- HEG05
- HEG06
- HEG07
- HEG08
- HEG09
- HEG10
- HEG11
- HEG12
- HEG13
- HEG14
- HEG15
- HEG16
- HEG17
- HEG18
- HEG19
- HEG20
- HEG21
- HEG22
- HEG23
- HEG24
- HEG25
- HEG26
- HEG27
- HEG28
- HEG29
- HEG30
- HEG31
- HEG32
- HEG33
- HEG34
- HEG35
- HEG36
- HEG37
- HEG38
- HEG39
- HEG40
- HEG41
- HEG42
- HEG43
- HEG44
- HEG45
- HEG46
- HEG47
- HEG48
- HEG49
- HEG50
- HET38
- HET44
- HEW01
- HEW02
- HEW03
- HEW04
- HEW05
- HEW06
- HEW07
- HEW08
- HEW09
- HEW10
- HEW11
- HEW12
- HEW13
- HEW14
- HEW15
- HEW16
- HEW17
- HEW18
- HEW19
- HEW20
- HEW21
- HEW22
- HEW23
- HEW24
- HEW25
- HEW26
- HEW27
- HEW28
- HEW29
- HEW30
- HEW31
- HEW32
- HEW33
- HEW34
- HEW35
- HEW36
- HEW37
- HEW38
- HEW39
- HEW40
- HEW41
- HEW42
- HEW43
- HEW44
- HEW45
- HEW46
- HEW47
- HEW48
- HEW49
- HEW50
- HEW51
- SEG01
- SEG02
- SEG03
- SEG04
- SEG05
- SEG06
- SEG07
- SEG08
- SEG09
- SEG10
- SEG11
- SEG12
- SEG13
- SEG14
- SEG15
- SEG16
- SEG17
- SEG18
- SEG19
- SEG20
- SEG21
- SEG22
- SEG23
- SEG24
- SEG25
- SEG26
- SEG27
- SEG28
- SEG29
- SEG30
- SEG31
- SEG32
- SEG33
- SEG34
- SEG35
- SEG36
- SEG37
- SEG38
- SEG39
- SEG40
- SEG41
- SEG42
- SEG43
- SEG44
- SEG45
- SEG46
- SEG47
- SEG48
- SEG49
- SEG50
- SET39
- SEW01
- SEW02
- SEW03
- SEW04
- SEW05
- SEW06
- SEW07
- SEW08
- SEW09
- SEW10
- SEW11
- SEW12
- SEW13
- SEW14
- SEW15
- SEW16
- SEW17
- SEW18
- SEW19
- SEW20
- SEW21
- SEW22
- SEW23
- SEW24
- SEW25
- SEW26
- SEW27
- SEW28
- SEW29
- SEW30
- SEW31
- SEW32
- SEW33
- SEW34
- SEW35
- SEW36
- SEW37
- SEW38
- SEW39
- SEW40
- SEW41
- SEW42
- SEW43
- SEW44
- SEW45
- SEW46
- SEW47
- SEW48
- SEW49
- SEW50
sensors:
- Ta_200
- P_RT_NRT
- P_RT_NRT_01
- P_RT_NRT_02
- P_RT_NRT_rain_days
- P_container_NRT
- P_container_RT
- p_local
- p_QNH
time interval:
  start: 2019-01-01T00:00
  end: 2019-12-31T23:00
aggregation: hour
quality check: empirical
interpolation: true
data columns:
- plotID
- datetime
data header: true
all plots in one file: true
data files: plots.csv
additional files:
- sensor_description.csv
- plot_description.csv
- processing_settings.yaml
